### ISSUE TITLE
Suggested RSpecs...

### ISSUE THREAD

**Issue by cscairns** [hzamani/acts_as_relation#10]
For those using the RSpec test suite, would be cool if some custom matchers were available:
1. should act_as_superclass
2. should act_as_parent
3. subclass should destroy when parent destroyed
4. parent should destroy when child subclass destroyed

**Comment by hzamani** [comment]
What kind of mathers are 3 and 4?

**Comment by JasperH8g** [comment]
How should we properly test at least the first 2?

**Comment by hzamani** [comment]
in `active_record-acts_as` there are `acting_as?` and `actable?` to check the first 2
