### ISSUE TITLE
Some methods not inheriting

### ISSUE THREAD

**Issue by RichardStokes** [hzamani/acts_as_relation#11]
Having some very strange issues with regards to child classes inheriting some parent methods

Here is one of the offending methods in my parent class:

def first_reccord
    self.profiled_appliances.first.first_reccord
end

here is my console readout:
x = Parent.first
y = Child.first
x.specific == y  # true
x.first_record # <Appliance>
y.first_reccord # NoMethodError: undefined method 'first_reccord' for <Child>

I don't understand why this is happening? Other parent methods are inheriting fine.

**Comment by hzamani** [comment]
what is `profiled_appliances`? is this an instance of `Parent` or `Child` or something else?

**Comment by RichardStokes** [comment]
Appliance is another one of my models. Parent has_many :appliances. Parent#profiled_appliances is as follows:

def profiled_appliances
    self.appliances.where(#some clause)
end

**Comment by hzamani** [comment]
Maybe there is a problem with `first_reccord` definition in `Appliance`. Can paste full exception message:

`NoMethodError: undefined method 'first_reccord' for ...` for what?

**Comment by RichardStokes** [comment]
Sorry for the delayed reply. Just revisited my code there to see was the error still there after developing other parts of the code further and it seems to have fixed itself. Must have been some small change I made without knowing that was causing the error.
