### ISSUE TITLE
attr_accessible in every model

### ISSUE THREAD

**Issue by bigardone** [hzamani/acts_as_relation#19]
Hi! First of all thanks for your plugin, it works great and it makes MTI very easy to implement for a Rails newbie like me.
The only issue I've found is that  have to write the attr_accessible in every class, instead of only doing it in my acts_as_superclass class... is this correct or am I doing something wrong?

**Comment by hzamani** [comment]
I don't think so, take a look at [dummy test](https://github.com/hzamani/acts_as_relation/tree/master/spec/dummy).

**Comment by hzamani** [comment]
Fixed in version 0.1.2
