### ISSUE TITLE
MultiparameterAssignmentErrors when passing date_select to parent class

### ISSUE THREAD

**Issue by nporteschaikin** [hzamani/acts_as_relation#22]
I have a model Resume with subclasses "Education" and "Employment." The parent class has time_start and time_end parameters. When I create a new Education object, for example, I receive a Multiparameter assignment error (two, actually - one for each select).

**Comment by hzamani** [comment]
what is your db schema?

**Comment by CrisSoFresh** [comment]
I had a similar issue with [Formtastic](https://github.com/justinfrench/formtastic) ([ActiveAdmin](https://github.com/gregbell/active_admin)), and the solution was to don't use 2 or 3 fields for date inputs, you should to use a single input with a date picker.

Good luck!
