### ISSUE TITLE
Model.columns doesn't show inherited columns

### ISSUE THREAD

**Issue by noelrocha** [hzamani/acts_as_relation#23]
if you do Model.columns it doesn't show inherited columns. It brokes things in ActiveAdmin for instance.

**Comment by noelrocha** [comment]
neither the Model.column_names

**Comment by hzamani** [comment]
Becuse there are not this models columns. Some time ago I tried to add inherited columns here but there was a problem, but I don't remember!

Did you tried to fix this?

**Comment by toobulkeh** [comment]
that would be incredibly valuable to my current problem

:+1: for a solution to this.

**Comment by hzamani** [comment]
in `active_record-acts_as` master branch `Model.attribute_names` includes supermodel attribute names.
