### ISSUE TITLE
AR has_one association broken?

### ISSUE THREAD

**Issue by agency-morizo** [hzamani/acts_as_relation#35]
In 1.0.0, the following in `lib/active_record/acts_as_relation.rb` (line 65) breaks using AR 3.2.13:

```
            singleton.send :define_method, :included do |base|
              base.has_one name.to_sym, scope, has_one_options

```

`has_one` accepts two arguments, so this raises an `ArgumentError (wrong number of arguments (3 for 2))`.

**Comment by hzamani** [comment]
1.0.0 depends on AR >= 4
for AR < 4 you have to stick with `gem 'acts_as_relation', '~> 1.0'`
