### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by activefx** [hzamani/acts_as_relation#39]
Is there any reason the :as_relation_superclass => true option does not add indexes to the product table such as: 

```
index :products, [:as_product_id, :as_product_type]
```

When looking up a subproduct that acts as a product the following sql is produced 

```
Product Load (53.7ms)  SELECT "products".* FROM "products" WHERE     "products"."as_product_id" = $1 AND "products"."as_product_type" = $2 ORDER BY "products"."id" ASC LIMIT 1  [["as_product_id", 1], ["as_product_type", "Products::Pen"]]
```

It makes sense to me that the :as_relation_superclass => true should add those indexes, or is that an exercise left to the developer? Maybe make a note of it in the readme?

**Comment by hzamani** [comment]
It should. Thanks

**Comment by hzamani** [comment]
Merged
Thanks
