### ISSUE TITLE
Association Type Mismatch error

### ISSUE THREAD

**Issue by kot-behemoth** [hzamani/acts_as_relation#41]
I'm having a strange issue with acts_as_relation. I have my (simplified) models structure as follows:

``` ruby
class User < ActiveRecord::Base
  has_one :occupation
end

class Occupation < ActiveRecord::Base
  acts_as_superclass

  belongs_to :user
  validates :user_id, presence: true
end

class Worker < ActiveRecord::Base
  acts_as :occupation, as: :occupation
end
```

In my migration, I used

``` ruby
  create_table "occupations", force: true do |t|
    t.integer "occupation_id"
    t.string  "occupation_type"
    t.integer "user_id"
  end
```

With this hierarchy (very similar to [bigardone's one](https://github.com/hzamani/acts_as_relation/issues/9#issuecomment-6627602)), I was expecting to be able to do the following simple assignment

``` ruby
user.occupation = Worker.new
```

however I'm getting this error:

``` ruby
ActiveRecord::AssociationTypeMismatch: Occupation expected, got Worker
```

I realised that you don't actually say this is possible anywhere in the docs, but I thought it would be. Currently, I'm working around this as follows:

``` ruby
user.occupation = Worker.new.occupation
```

which feels a bit like a hack.

I understand this is a very basic question, but I am relatively new to Rails, so I am wondering if I'm missing something?

**Comment by doncote** [comment]
I'm curious about this one as well.   I would expect polymorphism but maybe that's not the case?

**Comment by hzamani** [comment]
fixed
