### ISSUE TITLE
has_many :somethings << failing

### ISSUE THREAD

**Issue by mikebaldry** [hzamani/acts_as_relation#47]
Given these models:

``` ruby
class User < ActiveRecord::Base
  has_many :message_sources
end

class MessageSource < ActiveRecord::Base
  acts_as_superclass

  belongs_to :user, polymorphic: true
end

class TwitterMessageSource < ActiveRecord::Base
  acts_as :message_source
end
```

When I 

``` ruby
User.first.message_sources << TwitterMessageSource.new()
```

I get:

MessageSource(#70179625865060) expected, got TwitterMessageSource(#70179625930940)

**Comment by mariopeixoto** [comment]
The problem is that the class is 'acting as MessageSource' but does not inherit it. To make the << operator to work is necessary that the "subclass" returns true when the method twitter_message_source.is_a? MessageSource is invoked.

**Comment by hzamani** [comment]
fixed
