### ISSUE TITLE
Cannot use created_at or any timestamp columns to query: ambiguous column name

### ISSUE THREAD

**Issue by niiamon** [hzamani/acts_as_relation#57]
Fell into another issue here with acts_as_relation. From the dummy project in the acts_as_relation code, I run the migrations and then created a few objects. However, it's not possible to execute a query like this:

``` ruby
Pencil.where("created_at <= ?", Date.new())
```

You get an "ambiguous column name" error. Other than removing the created_at and updated_at columns on the subclasses or parent class, is there another way to get around this?

**Comment by barriault** [comment]
This works:

``` ruby
Pencil.where("pencils.created_at <= ?", Time.now)
```

**Comment by niiamon** [comment]
RIght. I'm going to give that a go. Thanks.
