### ISSUE TITLE
methods won't inherit

### ISSUE THREAD

**Issue by ftheo** [hzamani/acts_as_relation#6]
I followed the example line by line however when I call pen.hello I don't get anything just nil. Any suggestions?

**Comment by hzamani** [comment]
You are right, it's not working any more (If it was someday I don't know how!)
I made a quick fix on issue6 branch, but I think we have some tests missing! Pleas try it and let me know if there are problems with it.

**Comment by ftheo** [comment]
I don't know if this counts as an issue but if in the example the product has "has_many :sizes, :dependent => :destroy" then if you do pen.destroy the associated sizes will not be destroyed

**Comment by ftheo** [comment]
I made a quick fix for that however I haven't written any test for that. Now if you destroy the subclass the superclass will be destroyed as well

**Comment by ftheo** [comment]
I am also getting this error

/lib/active_record/acts/as_relation.rb:35: warning: already initialized constant AsMaster

**Comment by hzamani** [comment]
Can you show how to regenerate `already initialized constant` error?
