### ISSUE TITLE
Association field name error (assuming default convension names)

### ISSUE THREAD

**Issue by okliv** [hzamani/acts_as_relation#60]
if i have devices as superclass and add `device_id` and `device_type` fields to it 
i receive this 

```
Unknown column 'devices.as_device_id' in 'on clause': 
```

if i rename `device_id` to `as_device_...` everything works like expected

**Comment by hzamani** [comment]
super class require `as_device_id` and `as_device_type` column in databse
Use as_relation_superclass option on create table.
