### ISSUE TITLE
Name of the has_one assiocation

### ISSUE THREAD

**Issue by tomraulet** [hzamani/acts_as_relation#61]
Hi,

I use the ransack gem https://github.com/activerecord-hackery/ransack and i wnat to build a form with condition fields like describe in R. bates railscasts : http://railscasts.com/episodes/370-ransack

I start my form with my superclass model. I try to associate child classes but calling :

``` ruby
Superclass.first.childclass
```

says "NoMethodError"

Any ideas ?

Thanks in advance,

best regards

**Comment by mfoste** [comment]
Use Superclass.first.specific instead of Superclass.first.childclass?
