### ISSUE TITLE
Pen.where(name: "...") doesn't work

### ISSUE THREAD

**Issue by volkanunsal** [hzamani/acts_as_relation#62]
This might be an edgecase –– since `Pen.where("name = ?", "...")` is still working –– but I think this API is pretty widely used and would be cool to be able to use it.

Edit: just to be clear, I meant to write the subclass, not the superclass, in the issue title. This call from the superclass does in fact work.

**Comment by hzamani** [comment]
fixed in `active_record-acts_as` gem
